[build-system]
requires = ["maturin>=0.12"]
build-backend = "maturin"


[project]
name = "starfyre"
requires-python = ">=3.6"
dependencies=[]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


#######
# tox
#######

[tool.tox]
legacy_tox_ini = """

[config]
sources = {toxinidir}/starfyre


envlist =
    format
    mypy
    pylint


[testenv:format]
basepython = python3.10
skip_install = True
commands = 
    isort --atomic {[config]sources}
    black {[config]sources}
deps =
    isort
    black

[testenv:mypy]
basepython = python3.10
skip_install = True
commands = mypy {[config]sources}
deps =
    mypy

[testenv:pylint]
basepython = python3.10
skip_install = True
commands = pylint {[config]sources}
deps =
    pylint


"""

########
# mypy
########
[tool.mypy]
ignore_missing_imports = true
