[build-system]
requires = ["maturin>=0.12"]
build-backend = "maturin"


[project]
name = "starfyre"
requires-python = ">=3.6"
dependencies=[]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
